import type { NextApiRequest, NextApiResponse } from 'next';

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  const homeLayout = {
    status: 200,
    result: {
      page: 'HomePage',
      name: 'Trang chủ',
      blocks: [
        {
          name: 'HomeA',
          sections: [
            {
              name: 'HomeA_Main',
              listType: 'Tin nổi bật',
              cateId: null,
              cateAlias: null,
              title: '',
              isDisplayOnPage: true,
              includeChildCate: false,
              skip: 0,
              displayRatio: '16/9',
              randomArrange: false,
              displayOnPage: true,
            },
            {
              name: 'HomeA_Side',
              listType: 'Tin hỗn hợp',
              cateId: '6017e06d08d7227e0a6f730a',
              cateAlias: 'goc-nhin',
              title: 'Góc nhìn ',
              isDisplayOnPage: true,
              includeChildCate: true,
              skip: 0,
              displayRatio: '16/9',
              randomArrange: false,
              displayOnPage: true,
            },
          ],
        },
        {
          name: 'HomeB',
          sections: [
            {
              name: 'HomeB_Main',
              listType: 'Tin nổi bật',
              cateId: null,
              cateAlias: null,
              title: 'Theo dòng',
              isDisplayOnPage: true,
              includeChildCate: true,
              skip: 3,
              displayRatio: '16/9',
              randomArrange: false,
              displayOnPage: true,
            },
          ],
        },
        {
          name: 'HomeC',
          sections: [
            {
              name: 'HomeC_Main',
              listType: 'Tin hỗn hợp',
              cateId: '6662cd63738e750fca772681',
              cateAlias: 'kinh-te-xanh',
              title: 'Kinh tế xanh',
              isDisplayOnPage: true,
              includeChildCate: true,
              skip: 0,
              displayRatio: '16/9',
              randomArrange: false,
              displayOnPage: true,
            },
          ],
        },
        {
          name: 'HomeD',
          sections: [
            {
              name: 'HomeD_Main',
              listType: 'Tin hỗn hợp',
              cateId: '6662cd63738e750fca772681',
              cateAlias: 'kinh-te-xanh',
              title: 'Phát triển bền vững',
              isDisplayOnPage: true,
              includeChildCate: true,
              skip: 6,
              displayRatio: '16/9',
              randomArrange: false,
              displayOnPage: true,
            },
          ],
        },
        {
          name: 'HomeE',
          sections: [
            {
              name: 'HomeE_Main',
              listType: 'Tin hỗn hợp',
              cateId: '6662cd63738e750fca7726f0',
              cateAlias: 'di-trong-dat',
              title: 'Phóng sự - Ký sự',
              isDisplayOnPage: true,
              includeChildCate: true,
              skip: 0,
              displayRatio: 'ratioDefault',
              randomArrange: false,
              displayOnPage: true,
            },
          ],
        },
        {
          name: 'HomeF',
          sections: [
            {
              name: 'HomeF_Main',
              listType: 'Tin hỗn hợp',
              cateId: '6017e08008d7227e0a6f7322',
              cateAlias: 'nong-thon-moi',
              title: 'Nông thôn thịnh vượng',
              isDisplayOnPage: true,
              includeChildCate: true,
              skip: 0,
              displayRatio: '16/9',
              randomArrange: false,
              displayOnPage: true,
            },
          ],
        },
        {
          name: 'HomeG',
          sections: [
            {
              name: 'HomeG_Main',
              listType: 'Tin hỗn hợp',
              cateId: '6662cd63738e750fca7726f1',
              cateAlias: 'nguoi-que-toi',
              title: 'Người Quê Tôi',
              isDisplayOnPage: true,
              includeChildCate: true,
              skip: 0,
              displayRatio: '16/9',
              randomArrange: false,
              displayOnPage: true,
            },
          ],
        },
        {
          name: 'HomeH',
          sections: [
            {
              name: 'HomeH_Main',
              listType: 'Tin hỗn hợp',
              cateId: '60b9ebba8922ce5afaaed8e5',
              cateAlias: 'vi-cong-dong',
              title: 'Vì cộng đồng',
              isDisplayOnPage: true,
              includeChildCate: true,
              skip: 0,
              displayRatio: '16/9',
              randomArrange: false,
              displayOnPage: true,
            },
          ],
        },
        {
          name: 'HomeI',
          sections: [
            {
              name: 'HomeI_Main',
              listType: 'Tin hỗn hợp',
              cateId: '62300914b39100710b976f57',
              cateAlias: 'su-kien',
              title: 'Sự kiện doanh nghiệp',
              isDisplayOnPage: true,
              includeChildCate: true,
              skip: 0,
              displayRatio: '16/9',
              randomArrange: false,
              displayOnPage: true,
            },
          ],
        },
        {
          name: 'HomeJ',
          sections: [
            {
              name: 'HomeJ_1',
              listType: 'Tin hỗn hợp',
              cateId: '606c205bd5514b17fb0580a6',
              cateAlias: 'video',
              title: 'Video',
              isDisplayOnPage: true,
              includeChildCate: true,
              skip: 0,
              displayRatio: '16/9',
              randomArrange: false,
              displayOnPage: true,
            },
            {
              name: 'HomeJ_2',
              listType: 'Tin hỗn hợp',
              cateId: '621ee24fb39100710b1a214a',
              cateAlias: 'podcast',
              title: 'Podcast',
              isDisplayOnPage: true,
              includeChildCate: true,
              skip: 0,
              displayRatio: '16/9',
              randomArrange: false,
              displayOnPage: true,
            },
            {
              name: 'HomeJ_3',
              listType: 'Tin hỗn hợp',
              cateId: '611b70130963ee0a41330ae3',
              cateAlias: 'phong-su-anh',
              title: 'Ảnh',
              isDisplayOnPage: true,
              includeChildCate: true,
              skip: 0,
              displayRatio: '16/9',
              randomArrange: false,
              displayOnPage: true,
            },
          ],
        },
        {
          name: 'HomeK',
          sections: [
            {
              name: 'HomeK_Main',
              listType: 'Tin hỗn hợp',
              cateId: '6018d5343b03d94d646ad770',
              cateAlias: 'van-hoa',
              title: 'Sức sống mới',
              isDisplayOnPage: true,
              includeChildCate: true,
              skip: 0,
              displayRatio: '16/9',
              randomArrange: false,
              displayOnPage: true,
            },
          ],
        },
        {
          name: 'HomeL',
          sections: [
            {
              name: 'HomeL_Main',
              listType: 'Mặc định',
              cateId: '6017deb908d7227e0a6f7274',
              cateAlias: 'thoi-su',
              title: '',
              isDisplayOnPage: true,
              includeChildCate: true,
              skip: 0,
              displayRatio: '16/9',
              randomArrange: false,
              displayOnPage: true,
            },
          ],
        },
        {
          name: 'HomeM',
          sections: [
            {
              name: 'HomeM_Main',
              listType: 'Tin hỗn hợp',
              cateId: '6017e25708d7227e0a6f76eb',
              cateAlias: 'doi-song',
              title: '',
              isDisplayOnPage: true,
              includeChildCate: true,
              skip: 0,
              displayRatio: '16/9',
              randomArrange: false,
              displayOnPage: true,
            },
          ],
        },
        {
          name: 'HomeN',
          sections: [
            {
              name: 'HomeN_Main',
              listType: 'Tin hỗn hợp',
              cateId: '61925010369b3b7a63e91913',
              cateAlias: 'giai-tri',
              title: '',
              isDisplayOnPage: true,
              includeChildCate: true,
              skip: 0,
              displayRatio: '3/4',
              randomArrange: false,
              displayOnPage: true,
            },
          ],
        },
        {
          name: 'HomeO',
          sections: [
            {
              name: 'HomeO_Main',
              listType: 'Tin hỗn hợp',
              cateId: '6662cd63738e750fca77268e',
              cateAlias: 'xecong-nghe',
              title: 'Xe/Công nghệ',
              isDisplayOnPage: true,
              includeChildCate: true,
              skip: 0,
              displayRatio: '16/9',
              randomArrange: false,
              displayOnPage: true,
            },
          ],
        },
        {
          name: 'HomeP',
          sections: [
            {
              name: 'HomeP_Main',
              listType: 'Tin hỗn hợp',
              cateId: '62f0be902f16b160e4278828',
              cateAlias: 'song-khoe',
              title: 'Sống khỏe',
              isDisplayOnPage: true,
              includeChildCate: true,
              skip: 0,
              displayRatio: '16/9',
              randomArrange: false,
              displayOnPage: true,
            },
          ],
        },
      ],
    },
  };

  res.status(200).json(homeLayout);
}
